using Dapper;
using System.Collections.Generic;

namespace BlazorERP.Application.Database;

public class DbInitializer
{
    private const int CURRENT_DB_VERSION = 1;

    private readonly IDbConnectionFactory _dbConnectionFactory;

    public DbInitializer(IDbConnectionFactory dbConnectionFactory)
    {
        _dbConnectionFactory = dbConnectionFactory;
    }

    public async Task InitializeAsync()
    {
        using var connection = await _dbConnectionFactory.CreateConnectionAsync();

        string sql = "select 1 from rdb$relations where rdb$relation_name = 'ERP_CONFIG'";

        var tableExists = await connection.QuerySingleOrDefaultAsync<bool>(sql);

        if (!tableExists)
        {
            sql =
                """
                CREATE TABLE ERP_CONFIG 
                (
                    KEY_NAME VARCHAR(50) NOT NULL,
                    KEY_VALUE INTEGER NOT NULL,
                    PRIMARY KEY (KEY_NAME)
                );
                """;

            await connection.ExecuteAsync(sql);

            sql =
                """
                INSERT INTO ERP_CONFIG
                (
                    KEY_NAME,
                    KEY_VALUE
                )
                VALUES
                (
                    'DB_VERSION',
                    0
                )
                """;

            await connection.ExecuteAsync(sql);
        }


        sql = "SELECT KEY_VALUE FROM ERP_CONFIG WHERE KEY_NAME = 'DB_VERSION'";

        var dbVersion = await connection.QuerySingleAsync<int>(sql);

        if (dbVersion < CURRENT_DB_VERSION)
        {
            // First installation
            if (dbVersion < 1)
            {
                sql =
                    """
                    CREATE TABLE USERS 
                    (
                       	USER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       	USERNAME VARCHAR(50) NOT NULL,
                       	NORMALIZED_USERNAME VARCHAR(50) DEFAULT '' NOT NULL,
                       	FIRSTNAME VARCHAR(50) DEFAULT '' NOT NULL,
                       	LASTNAME VARCHAR(50) DEFAULT '' NOT NULL,
                       	DISPLAY_NAME VARCHAR(100) DEFAULT '' NOT NULL,
                       	ACTIVE_DIRECTORY_GUID VARCHAR(36),
                       	EMAIL VARCHAR(255) DEFAULT '' NOT NULL,
                       	PASSWORD VARCHAR(255) DEFAULT '' NOT NULL,
                       	SALT VARCHAR(255) DEFAULT '' NOT NULL,
                       	ACCOUNT_TYPE VARCHAR(20) DEFAULT 'LocalAccount' NOT NULL,
                       	IS_ACTIVE BOOLEAN DEFAULT FALSE NOT NULL,
                       	IS_ADMIN BOOLEAN DEFAULT FALSE NOT NULL,
                       	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       	CREATED_BY INTEGER DEFAULT NULL,
                       	LAST_MODIFIED_BY INTEGER DEFAULT NULL,
                        LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       	CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
                       	CONSTRAINT FK_USERS_CREATED FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID) ON UPDATE CASCADE ON DELETE SET NULL,
                       	CONSTRAINT FK_USERS_LAST FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES USERS(USER_ID) ON UPDATE CASCADE ON DELETE SET NULL
                    );
                    """;

                await connection.ExecuteAsync(sql);

                sql =
                    """
                    INSERT INTO USERS 
                    (
                        USER_ID, 
                        USERNAME, 
                        NORMALIZED_USERNAME, 
                        FIRSTNAME,  
                        PASSWORD,
                        SALT,
                        DISPLAY_NAME,  
                        IS_ACTIVE, 
                        IS_ADMIN
                    ) 
                    VALUES
                    (
                        @USER_ID, 
                        @USERNAME, 
                        @NORMALIZED_USERNAME, 
                        @FIRSTNAME, 
                        @PASSWORD,
                        @SALT,
                        @DISPLAY_NAME,  
                        @IS_ACTIVE, 
                        @IS_ADMIN    
                    );
                    """;



                await connection.ExecuteAsync(sql, new
                {
                    USER_ID = 1,
                    USERNAME = "erp_admin",
                    NORMALIZED_USERNAME = "ERP_ADMIN",
                    FIRSTNAME = "Administrator",
                    PASSWORD = "AQAAAAIAAYagAAAAENvHVp7Hx3Ws7rgflVnY0rWih9w6CHx276h82P3BFNAhL/eiOuDWB/Sd/qetKZKrOQ==",
                    SALT = "MKCiCF92oR",
                    DISPLAY_NAME = "Administrator",
                    IS_ACTIVE = true,
                    IS_ADMIN = true
                });

                sql =
                    """
                    CREATE TABLE LANGUAGES 
                    (
                    	LANGUAGE_ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    	CODE VARCHAR(20) NOT NULL,
                    	IS_ACTIVE BOOLEAN DEFAULT FALSE NOT NULL,
                    	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    	CREATED_BY INTEGER DEFAULT NULL,
                    	LAST_MODIFIED_BY INTEGER DEFAULT NULL,
                        LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    	CONSTRAINT PK_LANGUAGES PRIMARY KEY (LANGUAGE_ID),
                    	CONSTRAINT UK_LANGUAGES_CODE UNIQUE (CODE),
                    	CONSTRAINT FK_LANGUAGES_CREATED FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID) ON UPDATE CASCADE ON DELETE SET NULL,
                    	CONSTRAINT FK_LANGUAGES_LAST FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES USERS(USER_ID) ON UPDATE CASCADE ON DELETE SET NULL
                    );
                    """;

                await connection.ExecuteAsync(sql);


                sql =
                    """
                    CREATE TABLE TRANSLATIONS 
                    (
                        CODE VARCHAR(50) NOT NULL,
                        LANGUAGE_ID INTEGER NOT NULL,
                        PARENT_ID INTEGER NOT NULL,
                        VALUE_TEXT VARCHAR(255),
                        CONSTRAINT PK_TRANSLATIONS PRIMARY KEY (CODE, PARENT_ID, LANGUAGE_ID),
                        CONSTRAINT FK_TRANSLATIONS_LANGUAGE_ID FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGES(LANGUAGE_ID)
                    );
                    """;

                await connection.ExecuteAsync(sql);

                sql =
                    """
                    INSERT INTO LANGUAGES
                    (
                        LANGUAGE_ID, 
                        CODE, 
                        IS_ACTIVE, 
                        CREATED_BY, 
                        LAST_MODIFIED_BY
                    ) 
                    VALUES
                    (
                        @LANGUAGE_ID, 
                        @CODE, 
                        @IS_ACTIVE, 
                        @CREATED_BY, 
                        @LAST_MODIFIED_BY
                    );
                    """;

                await connection.ExecuteAsync(sql, new
                {
                    LANGUAGE_ID = 1,
                    CODE = "en-US",
                    IS_ACTIVE = true,
                    CREATED_BY = 1,
                    LAST_MODIFIED_BY = 1
                });
            
                await connection.ExecuteAsync(sql, new
                {
                    LANGUAGE_ID = 2,
                    CODE = "de-de",
                    IS_ACTIVE = true,
                    CREATED_BY = 1,
                    LAST_MODIFIED_BY = 1
                });

                sql =
                    """
                    INSERT INTO TRANSLATIONS
                    (
                        CODE, 
                        LANGUAGE_ID, 
                        PARENT_ID, 
                        VALUE_TEXT
                    ) 
                    VALUES
                    (
                        @CODE, 
                        @LANGUAGE_ID, 
                        @PARENT_ID, 
                        @VALUE_TEXT
                    );
                    """;

                await connection.ExecuteAsync(sql, new
                {
                    CODE = "LANGUAGE",
                    LANGUAGE_ID = 1,
                    PARENT_ID = 1,
                    VALUE_TEXT = "English (United States)"
                });

                await connection.ExecuteAsync(sql, new
                {
                    CODE = "LANGUAGE",
                    LANGUAGE_ID = 2,
                    PARENT_ID = 1,
                    VALUE_TEXT = "Englisch (United States)"
                });

                await connection.ExecuteAsync(sql, new
                {
                    CODE = "LANGUAGE",
                    LANGUAGE_ID = 1,
                    PARENT_ID = 2,
                    VALUE_TEXT = "German (Germany)"
                });

                await connection.ExecuteAsync(sql, new
                {
                    CODE = "LANGUAGE",
                    LANGUAGE_ID = 2,
                    PARENT_ID = 2,
                    VALUE_TEXT = "Deutsch (Deutschland)"
                });

                sql = "UPDATE ERP_CONFIG SET KEY_VALUE = 1 WHERE KEY_NAME = 'DB_VERSION'";
                await connection.ExecuteAsync(sql);
                dbVersion = 1;
            }
        }



        //await connection.ExecuteAsync(sql);


    }
}
