INSERT INTO ERP_CONFIG (CONFIG_KEY, CONFIG_VALUE) VALUES('DB_VERSION', 1);
INSERT INTO SPRACHEN (SPRACH_ID, NAME) VALUES (1, 'Deutsch');
INSERT INTO SPRACHEN (SPRACH_ID, NAME) VALUES (2, 'Englisch');

INSERT INTO UEBERSETZUNGEN (CODE,SPRACH_ID,PARENT_ID,VALUE_TEXT,VALUE_BLOB) VALUES ('LAND',2,1,'Germany',NULL);
INSERT INTO UEBERSETZUNGEN (CODE,SPRACH_ID,PARENT_ID,VALUE_TEXT,VALUE_BLOB) VALUES ('SPRACHE',2,1,'German',NULL);
INSERT INTO UEBERSETZUNGEN (CODE,SPRACH_ID,PARENT_ID,VALUE_TEXT,VALUE_BLOB) VALUES ('SPRACHE',2,2,'English',NULL);

INSERT INTO USERS (USER_ID, USERNAME, NORMALIZED_USERNAME, VORNAME, NACHNAME, ANZEIGENAME, ACTIVE_DIRECTORY_GUID, EMAIL, PASSWORD, SALT, ACCOUNT_TYPE, IS_AKTIV, IS_ADMIN) VALUES
(1,'erp_admin','ERP_ADMIN','Administrator','', 'Administrator',NULL,'','AQAAAAIAAYagAAAAENvHVp7Hx3Ws7rgflVnY0rWih9w6CHx276h82P3BFNAhL/eiOuDWB/Sd/qetKZKrOQ==','MKCiCF92oR','LocalAccount',true,true);


INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (1, 'Sehr geehrte Damen und Herren', 1);
INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (2, 'Sehr geehrte Frau', 1);
INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (3, 'Sehr geehrter Herr', 1);
INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (4, 'Sehr geehrter Herr Dr.', 1);
INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (5, 'Sehr geehrter Frau Dr.', 1);


INSERT INTO LAENDER (LAND_ID, NAME, ISO2, ISO3, VORWAHL, LETZTER_BEARBEITER) VALUES (1, 'Deutschland', 'DE', 'DEU', '+49', 1);

INSERT INTO WAEHRUNG (CODE, KURS, WECHSELKURS, MUSS_RUNDEN, NACHKOMMASTELLEN, KURS_VOM, LETZTER_BEARBEITER) VALUES ('EUR', 1, 1, FALSE, 2, CURRENT_TIMESTAMP, 1);



EXECUTE PROCEDURE RESEED_IDENTITY('SPRACHEN', 'SPRACH_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('USERS', 'USER_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('ANREDEN', 'ANREDE_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('LAENDER', 'LAND_ID');