INSERT INTO ERP_CONFIG (CONFIG_KEY, CONFIG_VALUE) VALUES('DB_VERSION', 1);
INSERT INTO SPRACHEN (SPRACH_ID, NAME) VALUES (1, 'Deutsch');
INSERT INTO SPRACHEN (SPRACH_ID, NAME) VALUES (2, 'Englisch');

INSERT INTO UEBERSETZUNGEN (CODE,SPRACH_ID,PARENT_ID,VALUE_TEXT,VALUE_BLOB) VALUES ('LAND',2,1,'Germany',NULL);
INSERT INTO UEBERSETZUNGEN (CODE,SPRACH_ID,PARENT_ID,VALUE_TEXT,VALUE_BLOB) VALUES ('SPRACHE',2,1,'German',NULL);
INSERT INTO UEBERSETZUNGEN (CODE,SPRACH_ID,PARENT_ID,VALUE_TEXT,VALUE_BLOB) VALUES ('SPRACHE',2,2,'English',NULL);

INSERT INTO USERS (USER_ID, USERNAME, NORMALIZED_USERNAME, VORNAME, NACHNAME, ACTIVE_DIRECTORY_GUID, EMAIL, PASSWORD, SALT, ACCOUNT_TYPE, IS_AKTIV, IS_ADMIN) VALUES
(1,'erp_admin','ERP_ADMIN','Administrator','',NULL,'','AQAAAAIAAYagAAAAENvHVp7Hx3Ws7rgflVnY0rWih9w6CHx276h82P3BFNAhL/eiOuDWB/Sd/qetKZKrOQ==','MKCiCF92oR','LocalAccount',true,true);
