INSERT INTO ERP_CONFIG (CONFIG_KEY, CONFIG_VALUE) VALUES('DB_VERSION', 1);

INSERT INTO USERS (USER_ID, USERNAME, NORMALIZED_USERNAME, FIRSTNAME, LASTNAME, DISPLAY_NAME, ACTIVE_DIRECTORY_GUID, EMAIL, PASSWORD, SALT, ACCOUNT_TYPE, IS_ACTIVE, IS_ADMIN) VALUES
(1,'erp_admin','ERP_ADMIN','Administrator','', 'Administrator',NULL,'','AQAAAAIAAYagAAAAENvHVp7Hx3Ws7rgflVnY0rWih9w6CHx276h82P3BFNAhL/eiOuDWB/Sd/qetKZKrOQ==','MKCiCF92oR','LocalAccount',true,true);

INSERT INTO LANGUAGES (LANGUAGE_ID, CODE, IS_ACTIVE, LAST_MODIFIED_BY) VALUES (1, 'en-US', TRUE, 1);
INSERT INTO LANGUAGES (LANGUAGE_ID, CODE, IS_ACTIVE, LAST_MODIFIED_BY) VALUES (2, 'de-de', TRUE, 1);

INSERT INTO TRANSLATIONS (CODE, LANGUAGE_ID, PARENT_ID, VALUE_TEXT) VALUES ('LANGUAGE', 1, 1, 'English (United States)');
INSERT INTO TRANSLATIONS (CODE, LANGUAGE_ID, PARENT_ID, VALUE_TEXT) VALUES ('LANGUAGE', 2, 1, 'Englisch (United States)');
INSERT INTO TRANSLATIONS (CODE, LANGUAGE_ID, PARENT_ID, VALUE_TEXT) VALUES ('LANGUAGE', 1, 2, 'German (Germany)');
INSERT INTO TRANSLATIONS (CODE, LANGUAGE_ID, PARENT_ID, VALUE_TEXT) VALUES ('LANGUAGE', 2, 2, 'Deutsch (Deutschland)');


INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (1, 'Sehr geehrte Damen und Herren', 1);
INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (2, 'Sehr geehrte Frau', 1);
INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (3, 'Sehr geehrter Herr', 1);
INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (4, 'Sehr geehrter Herr Dr.', 1);
INSERT INTO ANREDEN (ANREDE_ID, NAME, LETZTER_BEARBEITER) VALUES (5, 'Sehr geehrter Frau Dr.', 1);


INSERT INTO LAENDER (LAND_ID, NAME, ISO2, ISO3, VORWAHL, IST_EU, LETZTER_BEARBEITER) VALUES (1, 'Deutschland', 'DE', 'DEU', '+49', TRUE, 1);

INSERT INTO WAEHRUNG (CODE, KURS, WECHSELKURS, MUSS_RUNDEN, NACHKOMMASTELLEN, KURS_VOM, LETZTER_BEARBEITER) VALUES ('EUR', 1, 1, FALSE, 2, CURRENT_TIMESTAMP, 1);


INSERT INTO ZAHLUNGSBEDINGUNGEN (ZAHLUNGSBEDINGUNG_ID, NAME,IST_VORKASSE, IST_AKTIV, VERFUEGBAR_KUNDE, VERFUEGBAR_LIEFERANT, LETZTER_BEARBEITER) VALUES (1, 'Vorkasse', TRUE, TRUE, TRUE, TRUE, 1);

INSERT INTO LIEFERBEDINGUNGEN (LIEFERBEDINGUNG_ID, NAME, IST_AKTIV, VERFUEGBAR_KUNDE, VERFUEGBAR_LIEFERANT, LETZTER_BEARBEITER) VALUES (1, 'Versand Paketdienst', TRUE, TRUE, TRUE, 1);
INSERT INTO LIEFERBEDINGUNGEN (LIEFERBEDINGUNG_ID, NAME, IST_AKTIV, VERFUEGBAR_KUNDE, VERFUEGBAR_LIEFERANT, LETZTER_BEARBEITER) VALUES (2, 'Abholung durch Kunden', TRUE, TRUE, FALSE, 1);


INSERT INTO VOREINSTELLUNGEN (VOREINSTELLUNG_ID, NAME, KUNDE_LIEFERBEDINGUNG_ID, KUNDE_ZAHLUNGSBEDINGUNG_ID, KUNDE_ANREDE_ID, KUNDE_WAEHRUNGSCODE, KUNDE_LAND_ID, KUNDE_KREDITLIMIT, KUNDE_NEUTRALER_VERSAND, LETZTER_BEARBEITER) VALUES (1, 'Standard', 1, 1, 1, 'EUR', 1, 0, FALSE, 1);

INSERT INTO NUMMERNKREISE (NUMMERNKREIS_ID, NAME, KUNDE_VON, KUNDE_BIS, LETZTER_BEARBEITER) VALUES (1, 'Standard', 10000, 30000, 1);


EXECUTE PROCEDURE RESEED_IDENTITY('SPRACHEN', 'SPRACH_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('USERS', 'USER_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('ANREDEN', 'ANREDE_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('LAENDER', 'LAND_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('ZAHLUNGSBEDINGUNGEN', 'ZAHLUNGSBEDINGUNG_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('LIEFERBEDINGUNGEN', 'LIEFERBEDINGUNG_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('VOREINSTELLUNGEN', 'VOREINSTELLUNG_ID');
EXECUTE PROCEDURE RESEED_IDENTITY('NUMMERNKREISE', 'NUMMERNKREIS_ID');