CREATE OR ALTER TRIGGER GEN_KUNDENNUMMER
BEFORE INSERT ON KUNDEN
AS
BEGIN
    IF (NEW.KUNDENNUMMER IS NULL OR NEW.KUNDENNUMMER = '') THEN
    BEGIN
        NEW.KUNDENNUMMER = (SELECT NEXT_KUNDENNUMMER FROM GET_NEXT_KUNDENNUMMER) ;
    END
END

